Qna 0011
jhlee910609/reactjs-interview-questions pull request #15
Opened 2021-05-25 14:55 UTC by wndudqus

간단한 내용 번역했습니다. 확인 부탁드립니다.

2021-06-06 04:52 UTC, vlwkaos requested changes

2021-06-06 04:52 UTC, vlwkaos commented on README.md
> +|11 | [state를 직접 업데이트하면 안되는 이유.](#state를-직접-업데이트하면-안되는-이유) |
```suggestion
|11 | [상태(state)를 직접 업데이트하면 안되는 이유.](#상태state를-직접-업데이트하면-안되는-이유) |
```

2021-06-06 04:52 UTC, vlwkaos commented on README.md
> +11. ### state를 직접 업데이트하면 안되는 이유
```suggestion
11. ### 상태(state)를 직접 업데이트하면 안되는 이유
```

2021-06-06 04:52 UTC, vlwkaos commented on README.md
> +    만약 state를 직접 업데이트하려고 시도하면 component는 다시 렌더링 되지 않을 것입니다.
```suggestion
    상태(state)에 직접 접근하여 값을 변경하면 컴포넌트가 다시 렌더링 되지 않습니다.
```

2021-06-06 04:52 UTC, vlwkaos commented on README.md
> +    대신 `setState()` 메소드를 이용하세요. `setState()`는 component의 state 객체를 업데이트하도록 예약합니다. 이를 통해 state가 바뀌면 component는 다시 렌더링됩니다.
```suggestion
    대신 `setState()` 메소드를 이용해야합니다. `setState()`는 컴포넌트의 상태(state) 객체를 업데이트하도록 예약합니다. 이를 통해 상태(state)변화가 감지되면 component는 다시 렌더링됩니다.
```

2021-06-06 04:52 UTC, vlwkaos commented on README.md
> +     **Note:** 당신은 *constructor*메서드안에서나 javascript최신 문법인 class field declaration 문법을 이용해 state 객체에 직접 값을 할당할 수 있습니다.
```suggestion
     **Note:** 단, *생성자* 메소드나 자바스크립트의 클래스 변수 선언을 통해 상태(state)의 초기값을 직접 선언하는 것은 가능합니다.
```

2021-06-07 13:37 UTC, jhlee910609 approved these changes

2021-06-07 13:37 UTC, jhlee910609 commented on README.md
> +|11 | [state를 직접 업데이트하면 안되는 이유.](#state를-직접-업데이트하면-안되는-이유) |
```suggestion
|11 | [왜 상태(state)를 직접 업데이트하면 안되나요?](#왜-상태(state)를-직접-업데이트하면-안되나요) |
```

2021-06-07 13:37 UTC, jhlee910609 commented on README.md
> +|11 | [state를 직접 업데이트하면 안되는 이유.](#state를-직접-업데이트하면-안되는-이유) |
@wndudqus state => 상태(state) 로 용어 통일하기로 했어요.
https://github.com/jhlee910609/reactjs-interview-questions#용어-통일규칙

2021-06-07 13:37 UTC, merged