10번 번역완료
jhlee910609/reactjs-interview-questions pull request #16
Opened 2021-05-26 13:13 UTC by wndudqus

10번 번역완료 state 와 porps의 차이점에 대해서 번역했습니다.

2021-05-28 01:04 UTC, jhlee910609 reviewed
props에 대한 용어 통일이 필요할 것 같습니다.
@wndudqus @vlwkaos

2021-05-28 01:04 UTC, jhlee910609 commented on README.md
> +|10 | [props와 state의 차이점은 무엇인가요?](#props와-state의-차이점은-무엇인가요?) |
```suggestion
|10 | [props와 상태(state)의 차이점은 무엇인가요?](#props와-state의-차이점은-무엇인가요?) |
```

@wndudqus @vlwkaos props에 대한 한글 정의는 무엇으로 하는 게 좋을까요? '속성'이라고 정의한 글을 보긴 한 것 같아요.

2021-05-28 01:04 UTC, jhlee910609 commented on README.md
> +10. ### props와 state의 차이점은 무엇인가요?
```suggestion
10. ### props와 상태(state)의 차이점은 무엇인가요?
```
@wndudqus @vlwkaos props에 대한 한글 정의가 필요할듯요.
아래 내용에서도 state > 상태(state)로 용어 통일해주시면 좋을 것 같아요.

2021-06-01 13:15 UTC, wndudqus commented
수정사항 반영했습니다.

2021-06-06 04:46 UTC, vlwkaos commented on README.md
> +10. ### props와 state의 차이점은 무엇인가요?
속성(props)로 통일하져

2021-06-06 04:55 UTC, vlwkaos requested changes

2021-06-06 04:55 UTC, vlwkaos commented on README.md
> +|10 | [props와 상태(state)의 차이점은 무엇인가요?](#props와-state의-차이점은-무엇인가요?) |
```suggestion
|10 | [props와 상태(state)의 차이점은 무엇인가요?](#props와-상태state의-차이점은-무엇인가요?) |
```

2021-06-06 04:55 UTC, vlwkaos commented on README.md
> +    *props*와 *state* 모두 순수한 javascript 객체입니다. 두 객체 모두 렌더링 결과에 영행을 주는 정보를 가지고 있지만 component에 대한 기능이 다릅니다. props는 component에게 함수 파라미터와 유사하게 전달되는 반면, state는 함수내부에서 선언된 변수와 같이 component안에서 다뤄집니다.
```suggestion
    *속성(props)*와 *상태(state)* 모두 그저 자바스크립트의 객체입니다. 두 객체 모두 렌더링 결과에 영행을 주는 정보를 가지고 있지만 컴포넌트에 대한 기능이 다릅니다. 상태(props)는 함수의 인자와 유사하게 컴포넌트에 전달되는 반면, (상태)state는 함수내부에서 선언된 변수와 같이 컴포넌트내에서 다뤄집니다.
```

2021-06-07 13:35 UTC, merged