Feature/qna 0001
jhlee910609/reactjs-interview-questions pull request #4
Opened 2021-05-12 22:17 UTC by jhlee910609

plz, check!

2021-05-12 23:06 UTC, vlwkaos requested changes
봐주세용

2021-05-12 23:06 UTC, vlwkaos commented on README.md
> +- TODO
용어 통일/설명에 대한 항목을 만드는 것도 괜찮을거 같아여. 고유명사만 영어 그대로 쓴다던가

2021-05-12 23:06 UTC, vlwkaos commented on README.md
> +    리액트는 UI를 구성하기 위해 사용되는 자바스크립트 오픈소스 라이브러리 입니다. 특히, Single Page Application(SPA)로 구성되어 있는 프로젝트에서 자주 사용되며, 웹과 모바일에서 view 계층을 다루기 위해 사용됩니다. 리액트는 Facebook의 software 엔지니어인 [Jordan Walke](https://github.
```suggestion
    리액트는 UI를 구성하기 위해 사용되는 오픈소스 프론트엔드 자바스크립트 라이브러리 입니다. 특히, Single Page Application(SPA)로 구성되어 있는 프로젝트에서 자주 사용되며, 웹과 모바일에서 view 계층을 다루기 위해 사용됩니다. 리액트는 Facebook의 소프트웨어 엔지니어인 [Jordan Walke](https://github.com/jordwalke)이 만들었습니다. 리액트는 2011년 Facebook 뉴스피드 기능에 처음 사용되었고, 2012년에는 Instagram에 반영되었습니다.
```

2021-05-12 23:06 UTC, vlwkaos commented on README.md
> +|1  | [리액트란 무엇입니까?](#리액트란-무엇입니까) |
```suggestion
|1  | [React란 무엇입니까?](#React란-무엇입니까) |
```

2021-05-12 23:06 UTC, vlwkaos commented on README.md
> +1. ### 리액트란 무엇입니까?
```suggestion
1. ### React란 무엇입니까?
```

2021-05-13 14:05 UTC, wndudqus commented on README.md
> +- TODO
React는 고유명사니 그대로쓰는거 찬성합니다.

2021-05-13 14:06 UTC, wndudqus commented on README.md
> +    리액트는 UI를 구성하기 위해 사용되는 자바스크립트 오픈소스 라이브러리 입니다. 특히, Single Page Application(SPA)로 구성되어 있는 프로젝트에서 자주 사용되며, 웹과 모바일에서 view 계층을 다루기 위해 사용됩니다. 리액트는 Facebook의 software 엔지니어인 [Jordan Walke](https://github.
LGTM

2021-05-13 14:06 UTC, wndudqus approved these changes

2021-05-13 22:02 UTC, jhlee910609 commented on README.md
> +- TODO
React, Component... 뭐가 있을까요? 다음 번역에 추가해둘게요.

2021-05-14 22:25 UTC, vlwkaos approved these changes

2021-05-14 22:25 UTC, merged