feature/qna-0003 번역 완료
jhlee910609/reactjs-interview-questions pull request #6
Opened 2021-05-13 00:35 UTC by wndudqus

번역 완료했습니다.
링크가 잘 안먹어서 필요없는 커밋 많이 생성됐습니다.

2021-05-13 16:35 UTC, vlwkaos requested changes
조금 수정했습니다 반영 부탁드려요.

2021-05-13 16:35 UTC, vlwkaos commented on README.md
> +    *JSX* 는 XML과 비슷한 ECMAScript 확장 문법 입니다. (*JavaScript XML*의 약자). 기본적으로 `React.createElement()`함수를 쉽게 사용할 수 있도록 문법적인 이점을 제공하는 것이죠. 이 문법적 이점은 우리가 자바스크립트를 이용해 HTML과 비슷한 template 문법을 표현할 수 있도록 해줍니다.
```suggestion
    *JSX* 는 ECMAScript에 XML과 비슷한 문법을 사용할 수 있게 해줍니다.(*JavaScript XML*의 약자). 기본적으로 `React.createElement()`함수를 쉽게 사용할 수 있도록 문법적인 이점을 제공하는 것이죠. 이 문법적 이점은 우리가 자바스크립트를 이용해 HTML과 비슷한 template 문법을 표현할 수 있도록 해줍니다. 
```

2021-05-13 16:35 UTC, vlwkaos commented on README.md
> +  아래의 예시에서 `<h1>` tag 내부 문자는 자바스크립트 함수로 render 함수에게 return 됩니다.
```suggestion
  아래의 예시에서 `<h1>` 태그안의 내용은 render 함수 내에서 JavaScript 함수로 반환됩니다.
```

어떤가여

2021-05-14 13:20 UTC, wndudqus commented on README.md
> +  아래의 예시에서 `<h1>` tag 내부 문자는 자바스크립트 함수로 render 함수에게 return 됩니다.
반영 완료했습니다.

2021-05-14 13:20 UTC, wndudqus commented on README.md
> +    *JSX* 는 XML과 비슷한 ECMAScript 확장 문법 입니다. (*JavaScript XML*의 약자). 기본적으로 `React.createElement()`함수를 쉽게 사용할 수 있도록 문법적인 이점을 제공하는 것이죠. 이 문법적 이점은 우리가 자바스크립트를 이용해 HTML과 비슷한 template 문법을 표현할 수 있도록 해줍니다.
반영 완료했습니다.

2021-05-14 22:20 UTC, vlwkaos approved these changes

2021-05-14 22:21 UTC, merged