번역 완료
jhlee910609/reactjs-interview-questions pull request #8
Opened 2021-05-16 07:44 UTC by jhlee910609

2021-05-16 07:46 UTC, jhlee910609 reviewed
봐주세요

2021-05-16 07:46 UTC, jhlee910609 commented on README.md
> +     dispatcher, stores 그리고 views(components) 간의 작업 흐름은 다음과 뚜렷한 입/출력을 동반합니다.
번역했는데 의미는 알겠는데 한국어 표현이 잘 안돼요. help... @wndudqus @vlwkaos

2021-05-16 07:46 UTC, jhlee910609 commented on README.md
> +|  |  |
table 만듬요. @wndudqus @vlwkaos

2021-05-16 08:58 UTC, wndudqus commented on README.md
> +     dispatcher, stores 그리고 views(components) 간의 작업 흐름은 다음과 뚜렷한 입/출력을 동반합니다.
흠 저도 잘 모르겠네요..:( 고수 @vlwkaos help..

2021-05-16 14:36 UTC, vlwkaos requested changes
어떤가요?

2021-05-16 14:36 UTC, vlwkaos commented on README.md
> +     *Flux*는 고전적인 MVC 패턴을 대체하여 사용되는 application 설계 패러다임입니다. *Flux*는 프레임워크나 라이브러리가 아니라 React와 단반향 데이터 흐름(Unidirectional Data Flow)을 보완하기 위한 새로운 아키텍쳐의 한 종류입니다. Facebook 내부적으로 React를 사용할 때, 이 패턴을 사용합니다.
```suggestion
152. ### Flux란 무엇입니까?
     *Flux*는 프레임워크나 라이브러리가 아닌 React와 단방향 데이터 흐름(Unidirectional Data Flow)을 보완하는 새로운 어플리케이션 설계방식 입니다. *Flux*는 고전적인 MVC 패턴을 대체할 수 있습니다. Facebook 내부에서 React를 사용할 때 이 패턴을 사용합니다.
```

2021-05-16 14:36 UTC, vlwkaos commented on README.md
> +     dispatcher, stores 그리고 views(components) 간의 작업 흐름은 다음과 뚜렷한 입/출력을 동반합니다.
```suggestion
     dispatcher, stores, views간의 입/출력 데이터 흐름은 다음과 같습니다:
```

2021-05-17 13:33 UTC, jhlee910609 commented
github 정말 잘 만든듯요... @vlwkaos

2021-05-17 13:36 UTC, merged