25번 내용 번역, 0003번 들여쓰기 수정.
jhlee910609/reactjs-interview-questions pull request #9
Opened 2021-05-16 09:33 UTC by wndudqus

25번 Virtual DOM은 어떻게 동작하는가. 번역했습니다. 
그리고 0003번에서 들여쓰기 오류 수정했습니다.
확인 부탁드립니다.

2021-05-16 14:45 UTC, vlwkaos requested changes
확인해주세여

2021-05-16 14:45 UTC, vlwkaos commented on README.md
> +    *Virtual DOM*은 간단한 3개의 단계로 동작합니다.
```suggestion
    *Virtual DOM*은 간단한 3 가지 단계로 동작합니다.
```

2021-05-16 14:45 UTC, vlwkaos commented on README.md
> +    1. UI 내부의 데이터가 바뀔 때마다 모든 UI가 *Virtual DOM*표현으로 다시 렌더링 됩니다.
```suggestion
    1. 내부의 데이터가 바뀔 때마다 모든 UI가 *Virtual DOM*표현으로 다시 렌더링 됩니다.
```

2021-05-16 14:45 UTC, vlwkaos commented on README.md
> +    2. 그리고 이전 DOM표현과 새로 렌더링 된 것의 차이점이 계산됩니다.
```suggestion
    2. 그리고 이전 DOM표현과 새로 렌더링 된 것의 차이를 계산합니다.
```

2021-05-16 14:45 UTC, vlwkaos commented on README.md
> +    3. 계산이 끝나면, 실제 DOM은 실제로 바뀐 부분만 업데이트될 것입니다.
```suggestion
    3. 계산이 끝나면, 실제 DOM 중 바뀐 부분만 갱신됩니다.
```

2021-05-17 11:21 UTC, wndudqus commented
> 확인해주세여
수정완료했습니다.

2021-05-17 13:31 UTC, jhlee910609 reviewed
👍

2021-05-17 13:32 UTC, jhlee910609 commented
특별히 코멘트 남길 부분 없으니 merge 할게요.

2021-05-17 13:32 UTC, merged